title: SuperInfo Latino (A-H, 2024-25)
description: Link, date esami, registrazioni, appunti. C'è tutto.
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  input: GFM

# Exclude files you don’t want to be processed by Jekyll
exclude:
  - Gemfile
  - Gemfile.lock
